# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.1.6.dev6+g76b2599.d20220826'
__version_tuple__ = version_tuple = (3, 1, 6, 'dev6', 'g76b2599.d20220826')
